version: '3'

networks: 
    my-network:
        driver: bridge

services:
    postgres:
        image: postgres
        container_name: postgres
        ports:
            - "5432:5432"
        environment: 
            POSTGRES_USER: meuusuario
            POSTGRES_PASSWORD: minhasenha
            POSTGRES_DB: docker-postgres
        networks:
            - my-network

    adminer:
        image: adminer
        container_name: adminer
        ports:
            - "8080:8080"
        networks:
            - my-network
        depends_on: 
            - postgres
            
    mongodb:
        image: mongo:4
        container_name: mongodb
        ports:
            - "27017:27017"
        environment: 
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: senhaadmin
        networks:
            - my-network

    mongoclient:
        image: mongoclient/mongoclient
        container_name: mongoclient
        ports:
            - "3000:3000"
        networks:
            - my-network
        depends_on: 
            - mongodb
            